# BTS On-Time Performance: route profile (exploration)

Purpose: profile US domestic airport pairs so one route can be chosen to start the project with.
Exploration only: no modelling, no dbt models, and nothing in the data is cleaned or adjusted.
Anything that looks inconsistent is listed in section 3 rather than fixed.

**Source.** Bureau of Transportation Statistics (BTS), TranStats, *Marketing Carrier On-Time
Performance (Beginning January 2018)*, monthly pre-zipped CSV files:

`https://transtats.bts.gov/PREZIP/On_Time_Marketing_Carrier_On_Time_Performance_Beginning_January_2018_<YYYY>_<M>.zip`

Table page: <https://www.transtats.bts.gov/DL_SelectFields.aspx?gnoyr_VQ=FGK>

**How the data got here.** `ingestion/bts_otp.py` downloads the files into `data/raw/bts_otp_marketing/`
and loads them into the DuckDB table `raw.bts_otp_marketing`, every column as text with the original
names, plus `_source_file`, `_source_year`, `_source_month`. One row per file is written to
`raw.bts_otp_load_log`.

**To re-run.**

```bash
uv run python ingestion/bts_otp.py
uv run jupyter nbconvert --to notebook --execute --inplace notebooks/01_bts_otp_route_profile.ipynb
```

Every number below is produced by the SQL shown in the cell above it.

In [1]:
import os
from pathlib import Path

import duckdb
import pandas as pd

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 60)
pd.set_option("display.width", 250)
pd.set_option("display.max_colwidth", 120)

ROOT = Path.cwd() if (Path.cwd() / "pyproject.toml").exists() else Path.cwd().parent
DB = Path(os.environ.get("FLIGHT_DELAYS_DUCKDB_PATH", "data/flight_delays.duckdb"))
DB = DB if DB.is_absolute() else ROOT / DB
con = duckdb.connect(str(DB), read_only=True)
T = "raw.bts_otp_marketing"


def q(sql: str) -> pd.DataFrame:
    return con.sql(sql).df()


print("database:", DB.relative_to(ROOT) if DB.is_relative_to(ROOT) else DB)
print("duckdb:", duckdb.__version__)

database: data\flight_delays.duckdb
duckdb: 1.5.6

## 1. Files and rows per month

First the load log written by the ingestion script, then the same months counted from the table itself.

In [2]:
load_log = q("""
    SELECT month, zip_bytes, remote_last_modified, csv_data_lines, rows_loaded, n_columns, status
    FROM raw.bts_otp_load_log
    ORDER BY month
""")
load_log

      month  zip_bytes           remote_last_modified  csv_data_lines  rows_loaded  n_columns status
0   2023-01   30592621  Tue, 28 Mar 2023 12:31:31 GMT          573877       573877        123     ok
1   2023-02   27954550  Thu, 27 Apr 2023 11:59:20 GMT          536229       536229        123     ok
2   2023-03   32510491  Tue, 23 May 2023 11:20:53 GMT          616234       616234        123     ok
3   2023-04   31511282  Fri, 09 Jun 2023 17:55:00 GMT          596676       596676        123     ok
4   2023-05   31932462  Thu, 07 Sep 2023 13:28:51 GMT          616630       616630        123     ok
5   2023-06   32626440  Wed, 27 Sep 2023 12:42:29 GMT          613577       613577        123     ok
6   2023-07   33867598  Tue, 17 Oct 2023 14:24:48 GMT          638995       638995        123     ok
7   2023-08   33134150  Tue, 24 Oct 2023 13:24:02 GMT          640236       640236        123     ok
8   2023-09   31480933  Fri, 01 Dec 2023 13:14:01 GMT          604715       604715        123     ok
9   2023-10   33025323  Fri, 05 Jan 2024 14:04:42 GMT          635538       635538        123     ok
10  2023-11   31072754  Fri, 02 Feb 2024 13:56:24 GMT          599814       599814        123     ok
11  2023-12   32415374  Fri, 01 Mar 2024 16:22:47 GMT          606218       606218        123     ok
12  2024-01   31090329  Thu, 11 Apr 2024 17:42:42 GMT          582425       582425        123     ok
13  2024-02   28291928  Mon, 13 May 2024 13:17:07 GMT          552691       552691        123     ok
14  2024-03   32914089  Wed, 29 May 2024 16:25:52 GMT          628786       628786        123     ok
15  2024-04   32078032  Thu, 18 Jul 2024 12:39:08 GMT          619920       619920        123     ok
16  2024-05   35024172  Fri, 09 Aug 2024 12:42:28 GMT          649428       649428        123     ok
17  2024-06   35163767  Fri, 30 Aug 2024 13:55:48 GMT          651799       651799        123     ok
18  2024-07   38716020  Fri, 27 Sep 2024 15:26:17 GMT          676807       676807        123     ok
19  2024-08   34816042  Mon, 21 Oct 2024 14:19:54 GMT          660639       660639        123     ok
20  2024-09   32118312  Wed, 11 Dec 2024 13:05:48 GMT          621649       621649        123     ok
21  2024-10   33184224  Thu, 16 Jan 2025 19:10:27 GMT          656283       656283        123     ok
22  2024-11   31833594  Tue, 18 Feb 2025 18:43:52 GMT          614597       614597        123     ok
23  2024-12   34144173  Fri, 14 Mar 2025 16:18:45 GMT          631944       631944        123     ok
24  2025-01   31599374  Thu, 08 May 2025 14:59:14 GMT          599013       599013        123     ok
25  2025-02   29442140  Wed, 28 May 2025 14:21:48 GMT          559577       559577        123     ok
26  2025-03   35460382  Wed, 18 Jun 2025 14:37:32 GMT          664932       664932        123     ok
27  2025-04   34062432  Wed, 09 Jul 2025 14:32:53 GMT          644084       644084        123     ok
28  2025-05   35708775  Mon, 11 Aug 2025 14:35:07 GMT          667586       667586        123     ok
29  2025-06   36074147  Thu, 11 Sep 2025 14:34:47 GMT          674179       674179        123     ok
30  2025-07   37234575  Tue, 14 Oct 2025 14:36:08 GMT          696049       696049        123     ok
31  2025-08   35785563  Fri, 12 Dec 2025 13:30:57 GMT          666242       666242        123     ok
32  2025-09   32624136  Fri, 12 Dec 2025 13:36:37 GMT          621601       621601        123     ok
33  2025-10   35550100  Tue, 13 Jan 2026 14:49:55 GMT          668332       668332        123     ok
34  2025-11   33429487  Tue, 10 Feb 2026 13:15:59 GMT          630188       630188        123     ok
35  2025-12   35337872  Fri, 20 Mar 2026 12:51:15 GMT          644987       644987        123     ok
36  2026-01   32206577  Fri, 01 May 2026 17:51:29 GMT          602953       602953        123     ok
37  2026-02   30316996  Thu, 07 May 2026 12:48:52 GMT          568789       568789        123     ok
38  2026-03   36037927  Thu, 28 May 2026 14:50:40 GMT          675500       675500        123     ok
39  2026-04   35796979  Fri, 12 Jun 2026 13:44:10 GMT          660674       660674        123     ok
40  2026-05   37262815  Tue, 30 Jun 2026 18:01:24 GMT          677208       677208        123     ok
41  2026-06   37040545  Wed, 12 Aug 2026 12:15:23 GMT          671781       671781        123     ok
42  2026-07   38717338  Mon, 21 Sep 2026 17:57:57 GMT          697754       697754        123     ok

In [3]:
print(q("SELECT source_file, url FROM raw.bts_otp_load_log ORDER BY month LIMIT 1").T.to_string())
print()
print(
    q("""
    SELECT count(*) AS files,
           count(*) FILTER (WHERE status = 'ok') AS files_ok,
           count(*) FILTER (WHERE status <> 'ok') AS files_not_ok,
           count(*) FILTER (WHERE rows_loaded IS DISTINCT FROM csv_data_lines) AS files_row_count_differs,
           min(month) AS first_month, max(month) AS last_month,
           sum(rows_loaded) AS rows_loaded, sum(zip_bytes) AS zip_bytes
    FROM raw.bts_otp_load_log
""").T.to_string()
)

                                                                                                                            0
source_file                                   On_Time_Marketing_Carrier_On_Time_Performance_Beginning_January_2018_2023_1.zip
url          https://transtats.bts.gov/PREZIP/On_Time_Marketing_Carrier_On_Time_Performance_Beginning_January_2018_2023_1.zip

                                    0
files                              43
files_ok                           43
files_not_ok                        0
files_row_count_differs             0
first_month                   2023-01
last_month                    2026-07
rows_loaded                27117136.0
zip_bytes                1441186820.0

In [4]:
per_month = q(f"""
    WITH m AS (
        SELECT _source_year AS yr, _source_month AS mo,
               count(*) AS n_rows,
               count(DISTINCT FlightDate) AS distinct_flight_dates,
               day(last_day(make_date(_source_year, _source_month, 1))) AS days_in_month,
               min(FlightDate) AS min_flight_date,
               max(FlightDate) AS max_flight_date,
               count(*) FILTER (WHERE "Year" <> _source_year::VARCHAR
                                   OR "Month" <> _source_month::VARCHAR) AS rows_year_month_differs_from_file,
               count(*) FILTER (WHERE TRY_CAST(FlightDate AS DATE) IS NULL) AS rows_unparseable_flight_date,
               count(*) FILTER (WHERE year(TRY_CAST(FlightDate AS DATE)) <> _source_year
                                   OR month(TRY_CAST(FlightDate AS DATE)) <> _source_month) AS rows_flight_date_outside_month
        FROM {T}
        GROUP BY 1, 2
    )
    SELECT yr, mo, n_rows, distinct_flight_dates, days_in_month,
           round(n_rows / days_in_month) AS rows_per_day,
           round(100.0 * n_rows / lag(n_rows, 12) OVER (ORDER BY yr, mo) - 100, 1) AS pct_vs_same_month_prior_year,
           min_flight_date, max_flight_date,
           rows_year_month_differs_from_file, rows_unparseable_flight_date, rows_flight_date_outside_month
    FROM m
    ORDER BY yr, mo
""")
per_month

      yr  mo  n_rows  distinct_flight_dates  days_in_month  rows_per_day  pct_vs_same_month_prior_year min_flight_date max_flight_date  rows_year_month_differs_from_file  rows_unparseable_flight_date  rows_flight_date_outside_month
0   2023   1  573877                     31             31       18512.0                           NaN      2023-01-01      2023-01-31                                  0                             0                               0
1   2023   2  536229                     28             28       19151.0                           NaN      2023-02-01      2023-02-28                                  0                             0                               0
2   2023   3  616234                     31             31       19879.0                           NaN      2023-03-01      2023-03-31                                  0                             0                               0
3   2023   4  596676                     30             30       19889.0                           NaN      2023-04-01      2023-04-30                                  0                             0                               0
4   2023   5  616630                     31             31       19891.0                           NaN      2023-05-01      2023-05-31                                  0                             0                               0
5   2023   6  613577                     30             30       20453.0                           NaN      2023-06-01      2023-06-30                                  0                             0                               0
6   2023   7  638995                     31             31       20613.0                           NaN      2023-07-01      2023-07-31                                  0                             0                               0
7   2023   8  640236                     31             31       20653.0                           NaN      2023-08-01      2023-08-31                                  0                             0                               0
8   2023   9  604715                     30             30       20157.0                           NaN      2023-09-01      2023-09-30                                  0                             0                               0
9   2023  10  635538                     31             31       20501.0                           NaN      2023-10-01      2023-10-31                                  0                             0                               0
10  2023  11  599814                     30             30       19994.0                           NaN      2023-11-01      2023-11-30                                  0                             0                               0
11  2023  12  606218                     31             31       19555.0                           NaN      2023-12-01      2023-12-31                                  0                             0                               0
12  2024   1  582425                     31             31       18788.0                           1.5      2024-01-01      2024-01-31                                  0                             0                               0
13  2024   2  552691                     29             29       19058.0                           3.1      2024-02-01      2024-02-29                                  0                             0                               0
14  2024   3  628786                     31             31       20283.0                           2.0      2024-03-01      2024-03-31                                  0                             0                               0
15  2024   4  619920                     30             30       20664.0                           3.9      2024-04-01      2024-04-30                                  0                             0                               0
16  2024   5  649428                     31             31       20949.0                           5.3      2024-05-01      2024-05-31                                  0                             0                               0
17  2024   6  651799                     30             30       21727.0                           6.2      2024-06-01      2024-06-30                                  0                             0                               0
18  2024   7  676807                     31             31       21832.0                           5.9      2024-07-01      2024-07-31                                  0                             0                               0
19  2024   8  660639                     31             31       21311.0                           3.2      2024-08-01      2024-08-31                                  0                             0                               0
20  2024   9  621649                     30             30       20722.0                           2.8      2024-09-01      2024-09-30                                  0                             0                               0
21  2024  10  656283                     31             31       21170.0                           3.3      2024-10-01      2024-10-31                                  0                             0                               0
22  2024  11  614597                     30             30       20487.0                           2.5      2024-11-01      2024-11-30                                  0                             0                               0
23  2024  12  631944                     31             31       20385.0                           4.2      2024-12-01      2024-12-31                                  0                             0                               0
24  2025   1  599013                     31             31       19323.0                           2.8      2025-01-01      2025-01-31                                  0                             0                               0
25  2025   2  559577                     28             28       19985.0                           1.2      2025-02-01      2025-02-28                                  0                             0                               0
26  2025   3  664932                     31             31       21449.0                           5.7      2025-03-01      2025-03-31                                  0                             0                               0
27  2025   4  644084                     30             30       21469.0                           3.9      2025-04-01      2025-04-30                                  0                             0                               0
28  2025   5  667586                     31             31       21535.0                           2.8      2025-05-01      2025-05-31                                  0                             0                               0
29  2025   6  674179                     30             30       22473.0                           3.4      2025-06-01      2025-06-30                                  0                             0                               0
30  2025   7  696049                     31             31       22453.0                           2.8      2025-07-01      2025-07-31                                  0                             0                               0
31  2025   8  666242                     31             31       21492.0                           0.8      2025-08-01      2025-08-31                                  0                             0                               0
32  2025   9  621601                     30             30       20720.0                          -0.0      2025-09-01      2025-09-30                                  0                             0                               0
33  2025  10  668332                     31             31       21559.0                           1.8      2025-10-01      2025-10-31                                  0                             0                               0
34  2025  11  630188                     30             30       21006.0                           2.5      2025-11-01      2025-11-30                                  0                             0                               0
35  2025  12  644987                     31             31       20806.0                           2.1      2025-12-01      2025-12-31                                  0                             0                               0
36  2026   1  602953                     31             31       19450.0                           0.7      2026-01-01      2026-01-31                                  0                             0                               0
37  2026   2  568789                     28             28       20314.0                           1.6      2026-02-01      2026-02-28                                  0                             0                               0
38  2026   3  675500                     31             31       21790.0                           1.6      2026-03-01      2026-03-31                                  0                             0                               0
39  2026   4  660674                     30             30       22022.0                           2.6      2026-04-01      2026-04-30                                  0                             0                               0
40  2026   5  677208                     31             31       21845.0                           1.4      2026-05-01      2026-05-31                                  0                             0                               0
41  2026   6  671781                     30             30       22393.0                          -0.4      2026-06-01      2026-06-30                                  0                             0                               0
42  2026   7  697754                     31             31       22508.0                           0.2      2026-07-01      2026-07-31                                  0                             0                               0

Months expected between the first and last month loaded but absent from the table, and months whose distinct flight dates differ from the days in the month:

In [5]:
print(
    q(f"""
    WITH bounds AS (SELECT min(make_date(_source_year, _source_month, 1)) AS d0,
                           max(make_date(_source_year, _source_month, 1)) AS d1 FROM {T}),
         expected AS (SELECT unnest(generate_series(d0, d1, INTERVAL 1 MONTH))::DATE AS m FROM bounds),
         present AS (SELECT DISTINCT make_date(_source_year, _source_month, 1) AS m FROM {T})
    SELECT (SELECT count(*) FROM expected) AS months_expected,
           (SELECT count(*) FROM present) AS months_present,
           (SELECT list(strftime(e.m, '%Y-%m')) FROM expected e ANTI JOIN present p USING (m)) AS months_missing
""").T.to_string()
)
print()
print("months where distinct flight dates != days in month:")
print(
    per_month[per_month.distinct_flight_dates != per_month.days_in_month][
        ["yr", "mo", "distinct_flight_dates", "days_in_month"]
    ].to_string(index=False)
)

                    0
months_expected    43
months_present     43
months_missing   <NA>

months where distinct flight dates != days in month:
Empty DataFrame
Columns: [yr, mo, distinct_flight_dates, days_in_month]
Index: []

The 15 days with the fewest rows, with each day's share of the median daily row count of its own month (to spot partial days):

In [6]:
q(f"""
    WITH d AS (SELECT FlightDate, _source_year AS yr, _source_month AS mo, count(*) AS n_rows,
                      count(*) FILTER (WHERE Cancelled = '1.00') AS n_cancelled
               FROM {T} GROUP BY 1, 2, 3),
         x AS (SELECT *, median(n_rows) OVER (PARTITION BY yr, mo) AS month_median FROM d)
    SELECT FlightDate, dayname(FlightDate::DATE) AS weekday, n_rows, n_cancelled,
           month_median, round(100.0 * n_rows / month_median, 1) AS pct_of_month_median
    FROM x ORDER BY n_rows LIMIT 15
""")

    FlightDate   weekday  n_rows  n_cancelled  month_median  pct_of_month_median
0   2024-11-28  Thursday   11929            2       21421.0                 55.7
1   2025-11-27  Thursday   11963           18       21990.0                 54.4
2   2023-11-23  Thursday   12052            4       20738.5                 58.1
3   2023-01-14  Saturday   15844           34       18456.0                 85.8
4   2025-01-18  Saturday   16273           11       19988.0                 81.4
5   2023-01-21  Saturday   16414           25       18456.0                 88.9
6   2023-01-28  Saturday   16457          229       18456.0                 89.2
7   2024-01-13  Saturday   16501         1125       19251.0                 85.7
8   2024-02-03  Saturday   16546          246       19524.0                 84.7
9   2024-01-20  Saturday   16580          320       19251.0                 86.1
10  2024-01-27  Saturday   16591          287       19251.0                 86.2
11  2024-02-10  Saturday   16612           17       19524.0                 85.1
12  2025-01-11  Saturday   16633          752       19988.0                 83.2
13  2025-01-25  Saturday   16667           13       19988.0                 83.4
14  2024-12-24   Tuesday   16671          171       20877.0                 79.9

## 2. Every column and its null rate

All columns of the source file, in file order. A value counts as null when the CSV field is empty.
The three `_source_*` columns are added by the ingestion script and are listed last.

In [7]:
cols = [r[0] for r in con.sql(f"DESCRIBE {T}").fetchall()]
null_sql = (
    "SELECT count(*) AS n_rows, " + ", ".join(f'count("{c}") AS "{c}"' for c in cols) + f" FROM {T}"
)
print(null_sql[:400], "...", f"[{len(cols)} count() expressions, one per column]")
counts = con.sql(null_sql).df().iloc[0]
n_rows = int(counts["n_rows"])
nulls = pd.DataFrame(
    {
        "position": range(1, len(cols) + 1),
        "column": cols,
        "non_null": [int(counts[c]) for c in cols],
    }
)
nulls["nulls"] = n_rows - nulls["non_null"]
nulls["null_pct"] = (100 * nulls["nulls"] / n_rows).round(3)
print("rows:", n_rows, "| columns:", len(cols))
with pd.option_context("display.max_rows", None):
    display(nulls.set_index("position"))

SELECT count(*) AS n_rows, count("Year") AS "Year", count("Quarter") AS "Quarter", count("Month") AS "Month", count("DayofMonth") AS "DayofMonth", count("DayOfWeek") AS "DayOfWeek", count("FlightDate") AS "FlightDate", count("Marketing_Airline_Network") AS "Marketing_Airline_Network", count("Operated_or_Branded_Code_Share_Partners") AS "Operated_or_Branded_Code_Share_Partners", count("DOT_ID_Marke ... [123 count() expressions, one per column]

rows: 27117136 | columns: 123

                                                      column  non_null     nulls  null_pct
position
1                                                       Year  27117136         0     0.000
2                                                    Quarter  27117136         0     0.000
3                                                      Month  27117136         0     0.000
4                                                 DayofMonth  27117136         0     0.000
5                                                  DayOfWeek  27117136         0     0.000
6                                                 FlightDate  27117136         0     0.000
7                                  Marketing_Airline_Network  27117136         0     0.000
8                    Operated_or_Branded_Code_Share_Partners  27117136         0     0.000
9                                   DOT_ID_Marketing_Airline  27117136         0     0.000
10                               IATA_Code_Marketing_Airline  27117136         0     0.000
11                           Flight_Number_Marketing_Airline  27117135         1     0.000
12                   Originally_Scheduled_Code_Share_Airline      2371  27114765    99.991
13            DOT_ID_Originally_Scheduled_Code_Share_Airline      2371  27114765    99.991
14         IATA_Code_Originally_Scheduled_Code_Share_Airline      2371  27114765    99.991
15        Flight_Num_Originally_Scheduled_Code_Share_Airline      2371  27114765    99.991
16                                         Operating_Airline  27117136         0     0.000
17                                  DOT_ID_Operating_Airline  27117136         0     0.000
18                               IATA_Code_Operating_Airline  27117136         0     0.000
19                                               Tail_Number  27037555     79581     0.293
20                           Flight_Number_Operating_Airline  27117135         1     0.000
21                                           OriginAirportID  27117136         0     0.000
22                                        OriginAirportSeqID  27117136         0     0.000
23                                        OriginCityMarketID  27117136         0     0.000
24                                                    Origin  27117136         0     0.000
25                                            OriginCityName  27117136         0     0.000
26                                               OriginState  27117136         0     0.000
27                                           OriginStateFips  27117136         0     0.000
28                                           OriginStateName  27117136         0     0.000
29                                                 OriginWac  27117136         0     0.000
30                                             DestAirportID  27117136         0     0.000
31                                          DestAirportSeqID  27117136         0     0.000
32                                          DestCityMarketID  27117136         0     0.000
33                                                      Dest  27117136         0     0.000
34                                              DestCityName  27117136         0     0.000
35                                                 DestState  27117136         0     0.000
36                                             DestStateFips  27117136         0     0.000
37                                             DestStateName  27117136         0     0.000
38                                                   DestWac  27117136         0     0.000
39                                                CRSDepTime  27117136         0     0.000
40                                                   DepTime  26714108    403028     1.486
41                                                  DepDelay  26712891    404245     1.491
42                                           DepDelayMinutes  26712891    404245     1.491
43                                                  DepDel15  26712891    404245     1.491
44                                      DepartureDelayGroups  26712890    404246     1.491
45                                                DepTimeBlk  27117136         0     0.000
46                                                   TaxiOut  26699547    417589     1.540
47                                                 WheelsOff  26699547    417589     1.540
48                                                  WheelsOn  26689522    427614     1.577
49                                                    TaxiIn  26689522    427614     1.577
50                                                CRSArrTime  27117136         0     0.000
51                                                   ArrTime  26689525    427611     1.577
52                                                  ArrDelay  26624684    492452     1.816
53                                           ArrDelayMinutes  26624684    492452     1.816
54                                                  ArrDel15  26624684    492452     1.816
55                                        ArrivalDelayGroups  26624683    492453     1.816
56                                                ArrTimeBlk  27117136         0     0.000
57                                                 Cancelled  27117136         0     0.000
58                                          CancellationCode    420408  26696728    98.450
59                                                  Diverted  27117136         0     0.000
60                                            CRSElapsedTime  27117123        13     0.000
61                                         ActualElapsedTime  26624675    492461     1.816
62                                                   AirTime  26624675    492461     1.816
63                                                   Flights  27117136         0     0.000
64                                                  Distance  27117136         0     0.000
65                                             DistanceGroup  27117136         0     0.000
66                                              CarrierDelay   5694201  21422935    79.001
67                                              WeatherDelay   5694201  21422935    79.001
68                                                  NASDelay   5694201  21422935    79.001
69                                             SecurityDelay   5694201  21422935    79.001
70                                         LateAircraftDelay   5694201  21422935    79.001
71                                              FirstDepTime    199228  26917908    99.265
72                                             TotalAddGTime    199175  26917961    99.266
73                                           LongestAddGTime    199174  26917962    99.266
74                                        DivAirportLandings  27117129         7     0.000
75                                            DivReachedDest     72042  27045094    99.734
76                                      DivActualElapsedTime     64840  27052296    99.761
77                                               DivArrDelay     64841  27052295    99.761
78                                               DivDistance     72042  27045094    99.734
79                                               Div1Airport     74990  27042146    99.723
80                                             Div1AirportID     74989  27042147    99.723
81                                          Div1AirportSeqID     74989  27042147    99.723
82                                              Div1WheelsOn     74986  27042150    99.723
83                                            Div1TotalGTime     74989  27042147    99.723
84                                          Div1LongestGTime     74989  27042147    99.723
85                                             Div1WheelsOff     65349  27051787    99.759
86                                               Div1TailNum     65349  27051787    99.759
87                                               Div2Airport       749  27116387    99.997
88                                             Div2AirportID       750  27116386    99.997
89                                          Div2AirportSeqID       750  27116386    99.997
90                                              Div2WheelsOn       749  27116387    99.997
91                                            Div2TotalGTime       749  27116387    99.997
92                                          Div2LongestGTime       749  27116387    99.997
93                                             Div2WheelsOff       369  27116767    99.999
94                                               Div2TailNum       369  27116767    99.999
95                                               Div3Airport         8  27117128   100.000
96                                             Div3AirportID         9  27117127   100.000
97                                          Div3AirportSeqID         9  27117127   100.000
98                                              Div3WheelsOn         8  27117128   100.000
99                                            Div3TotalGTime         8  27117128   100.000
100                                         Div3LongestGTime         8  27117128   100.000
101                                            Div3WheelsOff         5  27117131   100.000
102                                              Div3TailNum         5  27117131   100.000
103                                              Div4Airport         0  27117136   100.000
104                                            Div4AirportID         0  27117136   100.000
105                                         Div4AirportSeqID         0  27117136   100.000
106                                             Div4WheelsOn         0  27117136   100.000
107                                           Div4TotalGTime         0  27117136   100.000
108                                         Div4LongestGTime         0  27117136   100.000
109                                            Div4WheelsOff         0  27117136   100.000
110                                              Div4TailNum         0  27117136   100.000
111                                              Div5Airport         0  27117136   100.000
112                                            Div5AirportID         0  27117136   100.000
113                                         Div5AirportSeqID         0  27117136   100.000
114                                             Div5WheelsOn         0  27117136   100.000
115                                           Div5TotalGTime         0  27117136   100.000
116                                         Div5LongestGTime         0  27117136   100.000
117                                            Div5WheelsOff         0  27117136   100.000
118                                              Div5TailNum         0  27117136   100.000
119                                                Duplicate  27117136         0     0.000
120                                                column119         0  27117136   100.000
121                                             _source_file  27117136         0     0.000
122                                             _source_year  27117136         0     0.000
123                                            _source_month  27117136         0     0.000

## 3. Consistency checks

Nothing here is corrected. Each line is a count of rows (or groups) matching a condition, so anything
non-zero that should be zero is visible.

In [8]:
for col in [
    "Cancelled",
    "Diverted",
    "Flights",
    "Duplicate",
    "CancellationCode",
    "DivAirportLandings",
]:
    print(
        q(f'SELECT "{col}", count(*) AS n_rows FROM {T} GROUP BY 1 ORDER BY 2 DESC').to_string(
            index=False
        )
    )
    print()

Cancelled   n_rows
     0.00 26696728
     1.00   420408

Diverted   n_rows
    0.00 27045094
    1.00    72042

Flights   n_rows
   1.00 27117136

Duplicate   n_rows
        N 27117136

CancellationCode   n_rows
             NaN 26696728
               B   254141
               A   101458
               C    64461
               D      348

DivAirportLandings   n_rows
                 0 27042146
                 1    71424
                 9     2941
                 2      611
               NaN        7
                 3        7

In [9]:
con.sql(f"""
    CREATE OR REPLACE TEMP VIEW otp AS
    SELECT TRY_CAST(FlightDate AS DATE) AS flight_date,
           Marketing_Airline_Network AS mkt, Operating_Airline AS op,
           Flight_Number_Marketing_Airline AS flt, Tail_Number AS tail,
           Origin AS origin, Dest AS dest, OriginAirportID AS origin_id, DestAirportID AS dest_id,
           OriginState AS origin_state, DestState AS dest_state,
           CRSDepTime AS crs_dep, DepTime AS dep_time, ArrTime AS arr_time,
           TRY_CAST(DepDelay AS DOUBLE) AS dep_delay,
           TRY_CAST(DepDelayMinutes AS DOUBLE) AS dep_delay_min,
           TRY_CAST(DepDel15 AS DOUBLE) AS dep_del15,
           TRY_CAST(ArrDelay AS DOUBLE) AS arr_delay,
           TRY_CAST(ArrDelayMinutes AS DOUBLE) AS arr_delay_min,
           TRY_CAST(ArrDel15 AS DOUBLE) AS arr_del15,
           TRY_CAST(Cancelled AS DOUBLE) AS cancelled,
           TRY_CAST(Diverted AS DOUBLE) AS diverted,
           TRY_CAST(Flights AS DOUBLE) AS flights,
           TRY_CAST(CarrierDelay AS DOUBLE) AS carrier_delay,
           TRY_CAST(WeatherDelay AS DOUBLE) AS weather_delay,
           TRY_CAST(NASDelay AS DOUBLE) AS nas_delay,
           TRY_CAST(SecurityDelay AS DOUBLE) AS security_delay,
           TRY_CAST(LateAircraftDelay AS DOUBLE) AS late_aircraft_delay
    FROM {T}
""")
checks = q("""
    SELECT
        count(*) AS rows_total,
        count(*) FILTER (WHERE cancelled IS NULL) AS cancelled_not_numeric_or_null,
        count(*) FILTER (WHERE diverted IS NULL) AS diverted_not_numeric_or_null,
        count(*) FILTER (WHERE cancelled = 1 AND diverted = 1) AS cancelled_and_diverted,
        count(*) FILTER (WHERE cancelled = 1 AND dep_time IS NOT NULL) AS cancelled_with_departure_time,
        count(*) FILTER (WHERE cancelled = 1 AND arr_time IS NOT NULL) AS cancelled_with_arrival_time,
        count(*) FILTER (WHERE cancelled = 0 AND dep_del15 IS NULL) AS not_cancelled_dep_del15_null,
        count(*) FILTER (WHERE cancelled = 0 AND diverted = 0 AND arr_del15 IS NULL) AS not_cancelled_not_diverted_arr_del15_null,
        count(*) FILTER (WHERE diverted = 1 AND arr_del15 IS NOT NULL) AS diverted_with_arr_del15,
        count(*) FILTER (WHERE dep_del15 = 1 AND dep_delay_min < 15) AS dep_del15_flag_but_under_15_min,
        count(*) FILTER (WHERE dep_del15 = 0 AND dep_delay_min >= 15) AS dep_del15_zero_but_15_plus_min,
        count(*) FILTER (WHERE arr_del15 = 1 AND arr_delay_min < 15) AS arr_del15_flag_but_under_15_min,
        count(*) FILTER (WHERE arr_del15 = 0 AND arr_delay_min >= 15) AS arr_del15_zero_but_15_plus_min,
        count(*) FILTER (WHERE arr_del15 = 1 AND carrier_delay IS NULL) AS arr_delayed_15_without_cause_minutes,
        count(*) FILTER (WHERE carrier_delay IS NOT NULL AND coalesce(arr_del15, 0) <> 1) AS cause_minutes_without_arr_del15,
        count(*) FILTER (WHERE carrier_delay IS NOT NULL
                           AND carrier_delay + weather_delay + nas_delay + security_delay + late_aircraft_delay
                               <> arr_delay_min) AS cause_minutes_sum_differs_from_arr_delay,
        count(*) FILTER (WHERE (carrier_delay IS NULL) <> (weather_delay IS NULL)
                            OR (carrier_delay IS NULL) <> (nas_delay IS NULL)
                            OR (carrier_delay IS NULL) <> (security_delay IS NULL)
                            OR (carrier_delay IS NULL) <> (late_aircraft_delay IS NULL)) AS cause_columns_partly_null,
        count(*) FILTER (WHERE origin = dest) AS origin_equals_dest,
        count(*) FILTER (WHERE flights <> 1 OR flights IS NULL) AS flights_column_not_1,
        count(*) FILTER (WHERE tail IS NULL) AS tail_number_null,
        count(*) FILTER (WHERE tail IS NULL AND cancelled = 0) AS tail_number_null_not_cancelled,
        count(*) FILTER (WHERE dep_delay > 1440) AS dep_delay_over_24h,
        max(dep_delay) AS max_dep_delay_min, min(dep_delay) AS min_dep_delay_min,
        max(arr_delay) AS max_arr_delay_min, min(arr_delay) AS min_arr_delay_min
    FROM otp
""").T
checks.columns = ["value"]
checks

                                                value
rows_total                                 27117136.0
cancelled_not_numeric_or_null                     0.0
diverted_not_numeric_or_null                      0.0
cancelled_and_diverted                            0.0
cancelled_with_departure_time                 17380.0
cancelled_with_arrival_time                       0.0
not_cancelled_dep_del15_null                      0.0
not_cancelled_not_diverted_arr_del15_null         2.0
diverted_with_arr_del15                           0.0
dep_del15_flag_but_under_15_min                   0.0
dep_del15_zero_but_15_plus_min                    0.0
arr_del15_flag_but_under_15_min                   0.0
arr_del15_zero_but_15_plus_min                    0.0
arr_delayed_15_without_cause_minutes              4.0
cause_minutes_without_arr_del15                   0.0
cause_minutes_sum_differs_from_arr_delay        120.0
cause_columns_partly_null                         0.0
origin_equals_dest                                0.0
flights_column_not_1                              0.0
tail_number_null                              79581.0
tail_number_null_not_cancelled                    0.0
dep_delay_over_24h                             2332.0
max_dep_delay_min                             10369.0
min_dep_delay_min                              -115.0
max_arr_delay_min                             10358.0
min_arr_delay_min                              -128.0

In [10]:
print(
    q("""
    WITH k AS (SELECT flight_date, mkt, flt, origin, dest, crs_dep, count(*) AS n
               FROM otp GROUP BY ALL HAVING count(*) > 1)
    SELECT count(*) AS duplicate_key_groups, coalesce(sum(n), 0) AS rows_in_those_groups,
           coalesce(sum(n) - count(*), 0) AS extra_rows
    FROM k
""").T.to_string()
)
print(
    "(key: flight date, marketing airline, marketing flight number, origin, destination, scheduled departure time)"
)
print()
print(
    q("""
    SELECT count(*) FILTER (WHERE n_ids > 1) AS airport_codes_with_more_than_one_airport_id,
           count(*) AS airport_codes
    FROM (SELECT origin, count(DISTINCT origin_id) AS n_ids FROM otp GROUP BY 1)
""").T.to_string()
)
print()
print("rows by origin state outside the 50 states and DC:")
print(
    q("""
    SELECT origin_state, count(*) AS n_rows FROM otp
    WHERE origin_state NOT IN ('AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN','IA','KS','KY',
        'LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI',
        'SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY') OR origin_state IS NULL
    GROUP BY 1 ORDER BY 2 DESC
""").to_string(index=False)
)

                        0
duplicate_key_groups  0.0
rows_in_those_groups  0.0
extra_rows            0.0
(key: flight date, marketing airline, marketing flight number, origin, destination, scheduled departure time)

                                               0
airport_codes_with_more_than_one_airport_id    0
airport_codes                                374

rows by origin state outside the 50 states and DC:

origin_state  n_rows
          PR  137834
          VI   23798
          TT    4429

## 4. Top 30 airport pairs by flight volume (each direction separately)

Definitions used in the three tables below:

- **Pair**: `Origin` → `Dest` airport codes; each direction is its own row. Ranked by row count.
- **Flights**: number of rows (one row is one scheduled flight; `sum(Flights)` is shown alongside as a check).
- **Average flights per day**: flights divided by the number of calendar days from the first to the last
  `FlightDate` in the whole table. `days_with_flights` shows how many of those days the pair actually operated.
- **Carriers**: distinct `Marketing_Airline_Network` and distinct `Operating_Airline` codes.
- **% delayed 15+**: `DepDel15` / `ArrDel15` equal to 1, as a share of flights where the flag is not null
  (cancelled flights have no flag; diverted flights have no arrival flag). The share of all scheduled
  flights is shown next to it.
- **% cancelled, % diverted, % null tail number**: share of all rows of the pair.
- **Delay minutes by cause**: sum of each cause column. BTS fills these only for flights that arrived
  15 or more minutes late; percentages are of the five causes' total.

In [11]:
TOP_SQL = """
    WITH period AS (
        SELECT min(flight_date) AS d0, max(flight_date) AS d1,
               datediff('day', min(flight_date), max(flight_date)) + 1 AS n_days
        FROM otp
    ),
    pairs AS (
        SELECT origin, dest,
               count(*) AS flights,
               sum(flights) AS sum_flights_column,
               count(DISTINCT flight_date) AS days_with_flights,
               count(DISTINCT mkt) AS n_marketing_carriers,
               count(DISTINCT op) AS n_operating_carriers,
               string_agg(DISTINCT mkt, ' ' ORDER BY mkt) AS marketing_carriers,
               string_agg(DISTINCT op, ' ' ORDER BY op) AS operating_carriers,
               count(dep_del15) AS dep_del15_reported,
               sum(dep_del15) AS dep_delayed_15,
               count(arr_del15) AS arr_del15_reported,
               sum(arr_del15) AS arr_delayed_15,
               sum(cancelled) AS cancelled,
               sum(diverted) AS diverted,
               count(*) FILTER (WHERE tail IS NULL) AS tail_null,
               coalesce(sum(carrier_delay), 0) AS carrier_min,
               coalesce(sum(weather_delay), 0) AS weather_min,
               coalesce(sum(nas_delay), 0) AS nas_min,
               coalesce(sum(security_delay), 0) AS security_min,
               coalesce(sum(late_aircraft_delay), 0) AS late_aircraft_min
        FROM otp
        GROUP BY origin, dest
    )
    SELECT row_number() OVER (ORDER BY flights DESC, origin, dest) AS rank, p.*, period.n_days,
           carrier_min + weather_min + nas_min + security_min + late_aircraft_min AS cause_min_total
    FROM pairs p, period
    QUALIFY rank <= 30
    ORDER BY rank
"""
top = q(TOP_SQL)
print(
    q(
        "SELECT min(flight_date) AS first_flight_date, max(flight_date) AS last_flight_date, "
        "datediff('day', min(flight_date), max(flight_date)) + 1 AS n_days, count(*) AS rows_total, "
        "count(DISTINCT origin || '-' || dest) AS directional_pairs FROM otp"
    ).T.to_string()
)
print("top 30 share of all rows: %.2f%%" % (100 * top.flights.sum() / n_rows))

                                     0
first_flight_date  2023-01-01 00:00:00
last_flight_date   2026-07-31 00:00:00
n_days                            1308
rows_total                    27117136
directional_pairs                 7965
top 30 share of all rows: 3.62%

### 4a. Volume and carriers

In [12]:
a = top[
    ["rank", "origin", "dest", "flights", "sum_flights_column", "n_days", "days_with_flights"]
].copy()
a.insert(4, "avg_flights_per_day", (top.flights / top.n_days).round(2))
a["n_marketing_carriers"] = top.n_marketing_carriers
a["n_operating_carriers"] = top.n_operating_carriers
a["marketing_carriers"] = top.marketing_carriers
a["operating_carriers"] = top.operating_carriers
a.set_index("rank")

     origin dest  flights  avg_flights_per_day  sum_flights_column  n_days  days_with_flights  n_marketing_carriers  n_operating_carriers       marketing_carriers             operating_carriers
rank
1       LAX  SFO    42204                32.27             42204.0    1308               1308                     7                     9     AA AS B6 DL F9 UA WN     AA AS B6 DL F9 OO QX UA WN
2       SFO  LAX    42141                32.22             42141.0    1308               1308                     7                    10     AA AS B6 DL F9 UA WN  AA AS B6 DL F9 MQ OO QX UA WN
3       OGG  HNL    40688                31.11             40688.0    1308               1308                     3                     3                 AS HA WN                       AS HA WN
4       HNL  OGG    40681                31.10             40681.0    1308               1308                     3                     3                 AS HA WN                       AS HA WN
5       LGA  ORD    39202                29.97             39202.0    1308               1308                     4                     7              AA DL NK UA           9E AA DL NK OO UA YX
6       ORD  LGA    39200                29.97             39200.0    1308               1308                     4                     7              AA DL NK UA           9E AA DL NK OO UA YX
7       JFK  LAX    36087                27.59             36087.0    1308               1308                     4                     4              AA B6 DL F9                    AA B6 DL F9
8       LAX  JFK    36086                27.59             36086.0    1308               1308                     4                     4              AA B6 DL F9                    AA B6 DL F9
9       LAX  LAS    35707                27.30             35707.0    1308               1308                     8                    10  AA AS B6 DL F9 NK UA WN  AA AS B6 DL F9 NK OO QX UA WN
10      LAS  LAX    35672                27.27             35672.0    1308               1308                     8                    10  AA AS B6 DL F9 NK UA WN  AA AS B6 DL F9 NK OO QX UA WN
11      BOS  DCA    33923                25.94             33923.0    1308               1308                     3                     5                 AA B6 DL                 AA B6 DL MQ YX
12      DCA  BOS    33923                25.94             33923.0    1308               1308                     3                     5                 AA B6 DL                 AA B6 DL MQ YX
13      PHX  DEN    33412                25.54             33412.0    1308               1308                     4                     7              AA F9 UA WN           AA F9 MQ OO UA WN YV
14      DEN  PHX    33314                25.47             33314.0    1308               1308                     4                     7              AA F9 UA WN           AA F9 MQ OO UA WN YV
15      MCO  ATL    31120                23.79             31120.0    1308               1308                     4                     4              DL F9 NK WN                    DL F9 NK WN
16      ATL  MCO    31106                23.78             31106.0    1308               1308                     4                     4              DL F9 NK WN                    DL F9 NK WN
17      LIH  HNL    29826                22.80             29826.0    1308               1308                     3                     3                 AS HA WN                       AS HA WN
18      HNL  LIH    29820                22.80             29820.0    1308               1308                     3                     3                 AS HA WN                       AS HA WN
19      DEN  LAS    29029                22.19             29029.0    1308               1308                     4                     4              F9 NK UA WN                    F9 NK UA WN
20      LAS  DEN    29013                22.18             29013.0    1308               1308                     4                     4              F9 NK UA WN                    F9 NK UA WN
21      ATL  LGA    28490                21.78             28490.0    1308               1308                     6                     7        AA B6 DL F9 NK WN           AA B6 DL F9 NK WN YX
22      LGA  ATL    28485                21.78             28485.0    1308               1308                     6                     7        AA B6 DL F9 NK WN           AA B6 DL F9 NK WN YX
23      DEN  SLC    28149                21.52             28149.0    1308               1308                     4                     5              DL F9 UA WN                 DL F9 OO UA WN
24      SLC  DEN    28117                21.50             28117.0    1308               1308                     4                     5              DL F9 UA WN                 DL F9 OO UA WN
25      KOA  HNL    27997                21.40             27997.0    1308               1308                     3                     3                 AS HA WN                       AS HA WN
26      HNL  KOA    27993                21.40             27993.0    1308               1308                     3                     3                 AS HA WN                       AS HA WN
27      LGA  BOS    27382                20.93             27382.0    1308               1308                     3                     4                 AA B6 DL                    AA B6 DL YX
28      BOS  LGA    27375                20.93             27375.0    1308               1308                     4                     5              AA B6 DL NK                 AA B6 DL NK YX
29      DEN  LAX    27269                20.85             27269.0    1308               1308                     6                     7        AA DL F9 NK UA WN           AA DL F9 NK OO UA WN
30      LAX  DEN    27209                20.80             27209.0    1308               1308                     6                     7        AA DL F9 NK UA WN           AA DL F9 NK OO UA WN

### 4b. Delays, cancellations, diversions, tail numbers

In [13]:
b = top[["rank", "origin", "dest", "flights"]].copy()
b["pct_dep_delayed_15_of_reported"] = (100 * top.dep_delayed_15 / top.dep_del15_reported).round(2)
b["pct_arr_delayed_15_of_reported"] = (100 * top.arr_delayed_15 / top.arr_del15_reported).round(2)
b["pct_dep_delayed_15_of_scheduled"] = (100 * top.dep_delayed_15 / top.flights).round(2)
b["pct_arr_delayed_15_of_scheduled"] = (100 * top.arr_delayed_15 / top.flights).round(2)
b["pct_cancelled"] = (100 * top.cancelled / top.flights).round(2)
b["pct_diverted"] = (100 * top.diverted / top.flights).round(2)
b["tail_null_rows"] = top.tail_null
b["pct_tail_null"] = (100 * top.tail_null / top.flights).round(3)
b.set_index("rank")

     origin dest  flights  pct_dep_delayed_15_of_reported  pct_arr_delayed_15_of_reported  pct_dep_delayed_15_of_scheduled  pct_arr_delayed_15_of_scheduled  pct_cancelled  pct_diverted  tail_null_rows  pct_tail_null
rank
1       LAX  SFO    42204                           24.33                           30.11                            24.14                            29.81           0.81          0.18             110          0.261
2       SFO  LAX    42141                           23.42                           22.87                            23.22                            22.66           0.90          0.04             115          0.273
3       OGG  HNL    40688                           12.78                           15.55                            12.63                            15.36           1.20          0.02             336          0.826
4       HNL  OGG    40681                           12.00                           13.76                            11.88                            13.62           1.03          0.03             286          0.703
5       LGA  ORD    39202                           20.68                           24.35                            20.05                            23.48           3.30          0.27             428          1.092
6       ORD  LGA    39200                           24.41                           26.30                            23.69                            25.33           3.16          0.53             391          0.997
7       JFK  LAX    36087                           17.40                           20.63                            17.24                            20.37           1.11          0.18               3          0.008
8       LAX  JFK    36086                           20.66                           20.27                            20.42                            19.92           1.19          0.55               1          0.003
9       LAX  LAS    35707                           23.58                           24.35                            23.36                            24.11           0.94          0.04              71          0.199
10      LAS  LAX    35672                           23.83                           23.73                            23.63                            23.51           0.90          0.02              52          0.146
11      BOS  DCA    33923                           19.45                           21.68                            18.95                            21.05           2.64          0.26              18          0.053
12      DCA  BOS    33923                           22.86                           23.00                            22.27                            22.36           2.73          0.07              18          0.053
13      PHX  DEN    33412                           22.95                           21.41                            22.73                            21.15           1.01          0.22             112          0.335
14      DEN  PHX    33314                           26.34                           24.66                            26.08                            24.39           1.00          0.09              99          0.297
15      MCO  ATL    31120                           24.99                           25.94                            24.70                            25.59           1.20          0.14              98          0.315
16      ATL  MCO    31106                           27.99                           28.78                            27.66                            28.35           1.22          0.28             106          0.341
17      LIH  HNL    29826                           12.60                           15.75                            12.43                            15.54           1.30          0.01             318          1.066
18      HNL  LIH    29820                           12.76                           14.52                            12.61                            14.34           1.17          0.05             282          0.946
19      DEN  LAS    29029                           28.24                           26.70                            27.93                            26.38           1.10          0.09             128          0.441
20      LAS  DEN    29013                           25.51                           24.59                            25.20                            24.23           1.29          0.21             159          0.548
21      ATL  LGA    28490                           25.86                           23.44                            25.29                            22.75           2.38          0.54             130          0.456
22      LGA  ATL    28485                           22.48                           21.41                            21.96                            20.84           2.46          0.20             159          0.558
23      DEN  SLC    28149                           25.70                           23.50                            25.52                            23.30           0.72          0.10              50          0.178
24      SLC  DEN    28117                           20.31                           23.02                            20.16                            22.78           0.80          0.25              73          0.260
25      KOA  HNL    27997                           12.45                           14.65                            12.32                            14.48           1.10          0.01             229          0.818
26      HNL  KOA    27993                           12.38                           13.71                            12.26                            13.57           0.97          0.04             204          0.729
27      LGA  BOS    27382                           20.39                           20.75                            19.68                            19.99           3.60          0.07              32          0.117
28      BOS  LGA    27375                           18.93                           18.94                            18.23                            18.20           3.89          0.07              38          0.139
29      DEN  LAX    27269                           23.68                           21.88                            23.49                            21.69           0.81          0.05              95          0.348
30      LAX  DEN    27209                           18.95                           17.67                            18.79                            17.47           0.84          0.29             102          0.375

### 4c. Delay minutes by cause

In [14]:
c = top[
    [
        "rank",
        "origin",
        "dest",
        "carrier_min",
        "weather_min",
        "nas_min",
        "security_min",
        "late_aircraft_min",
        "cause_min_total",
    ]
].copy()
for name in ["carrier", "weather", "nas", "security", "late_aircraft"]:
    c[f"pct_{name}"] = (100 * top[f"{name}_min"] / top.cause_min_total).round(1)
for name in [
    "carrier_min",
    "weather_min",
    "nas_min",
    "security_min",
    "late_aircraft_min",
    "cause_min_total",
]:
    c[name] = c[name].astype("int64")
c.set_index("rank")

     origin dest  carrier_min  weather_min  nas_min  security_min  late_aircraft_min  cause_min_total  pct_carrier  pct_weather  pct_nas  pct_security  pct_late_aircraft
rank
1       LAX  SFO       167310        10959   336288           483             220786           735826         22.7          1.5     45.7           0.1               30.0
2       SFO  LAX       155795         8115    92990           388             338527           595815         26.1          1.4     15.6           0.1               56.8
3       OGG  HNL        71889         7229    33019           395             150635           263167         27.3          2.7     12.5           0.2               57.2
4       HNL  OGG       104594         5876    11743           565              93020           215798         48.5          2.7      5.4           0.3               43.1
5       LGA  ORD       199218        46222   238821           493             328661           813415         24.5          5.7     29.4           0.1               40.4
6       ORD  LGA       208328        34783   255676           578             303249           802614         26.0          4.3     31.9           0.1               37.8
7       JFK  LAX       241842        17682   146635           726             144128           551013         43.9          3.2     26.6           0.1               26.2
8       LAX  JFK       279423         3647   147822          1110             229368           661370         42.2          0.6     22.4           0.2               34.7
9       LAX  LAS       136580         7152   160464           920             240635           545751         25.0          1.3     29.4           0.2               44.1
10      LAS  LAX       158866        16053    87400           745             276174           539238         29.5          3.0     16.2           0.1               51.2
11      BOS  DCA       144408        13183   161523           474             215266           534854         27.0          2.5     30.2           0.1               40.2
12      DCA  BOS       135972        15757   179408           357             279666           611160         22.2          2.6     29.4           0.1               45.8
13      PHX  DEN       123056         8555   117295           407             209444           458757         26.8          1.9     25.6           0.1               45.7
14      DEN  PHX       170329        11088    69939           481             255729           507566         33.6          2.2     13.8           0.1               50.4
15      MCO  ATL       176502        31853   150656          1369             264711           625091         28.2          5.1     24.1           0.2               42.3
16      ATL  MCO       245547        21435   172865          1005             193726           634578         38.7          3.4     27.2           0.2               30.5
17      LIH  HNL        46300         9012    24840           334             116782           197268         23.5          4.6     12.6           0.2               59.2
18      HNL  LIH        73545         6727     7507           591              83411           171781         42.8          3.9      4.4           0.3               48.6
19      DEN  LAS       128827        13741   111414           377             220248           474607         27.1          2.9     23.5           0.1               46.4
20      LAS  DEN       113518        14637   113811           567             215294           457827         24.8          3.2     24.9           0.1               47.0
21      ATL  LGA       147922        19855   161211           946             127449           457383         32.3          4.3     35.2           0.2               27.9
22      LGA  ATL       151994        11131   105366           368             190769           459628         33.1          2.4     22.9           0.1               41.5
23      DEN  SLC       154198        16128    48431           539             190077           409373         37.7          3.9     11.8           0.1               46.4
24      SLC  DEN       140440        19742   124561           117             130399           415259         33.8          4.8     30.0           0.0               31.4
25      KOA  HNL        42217         6353    18446           227             107464           174707         24.2          3.6     10.6           0.1               61.5
26      HNL  KOA        70392         3950     8013           514              62981           145850         48.3          2.7      5.5           0.4               43.2
27      LGA  BOS       113455         8807   133736           306             157334           413638         27.4          2.1     32.3           0.1               38.0
28      BOS  LGA       107324        16198   144648           345             116437           384952         27.9          4.2     37.6           0.1               30.2
29      DEN  LAX       146853        13368    48511           463             174172           383367         38.3          3.5     12.7           0.1               45.4
30      LAX  DEN        99839         7553    87052           234             120601           315279         31.7          2.4     27.6           0.1               38.3

### 4d. Checks on the top 30

In [15]:
print("pairs where count(*) != sum(Flights):", int((top.flights != top.sum_flights_column).sum()))
print(
    "pairs not operated on every day of the period:",
    int((top.days_with_flights != top.n_days).sum()),
)
rev = top.merge(top, left_on=["origin", "dest"], right_on=["dest", "origin"], suffixes=("", "_rev"))
print("pairs whose reverse direction is also in the top 30:", len(rev), "of", len(top))
print("top-30 pairs whose reverse direction is NOT in the top 30:")
print(
    top[~top.set_index(["origin", "dest"]).index.isin(rev.set_index(["origin", "dest"]).index)][
        ["rank", "origin", "dest", "flights"]
    ].to_string(index=False)
)

pairs where count(*) != sum(Flights): 0
pairs not operated on every day of the period: 0
pairs whose reverse direction is also in the top 30: 30 of 30
top-30 pairs whose reverse direction is NOT in the top 30:
Empty DataFrame
Columns: [rank, origin, dest, flights]
Index: []

In [16]:
con.close()